env:
  global:
    - GH_REF: github.com/Zheaoli/zheaoli.github.io.git
    - secure: "oFvDE0X5JtQTz0D5CSwF2eqJ5QPXb8coo5zKMogHCloKSyAqWG7CUj5OLTvTSJD/ESnrWAjjNr4EKVc11GjTcnWtsDjRZJIxjVXa2sEXcOn5s2ya4tVn9o1waMkb0/6Q69R2R4+v4zixAnWhncDRDhnLlTIhQ6/5SOHQTQZHTSj1XXAXDY0NlMK2iuAAUH6rIK1f7i+Cb1E0tJFjUZKwKMhvfZ8PEUDBEP3OBtN3qMZJAQ7WHnHIoTle0v/YbdqDCaATXDbE41JI35dgfEm4mTSK/Wp55qMXE8EN0hZLxIm2aE5bjOWZVBc9jEJAFi/30TrAJheM1NoTjA/gHkKQnWZD5evxVXMVvTV6wtN99X4n3notJC3eeL8Y7h6rdCcjFqrZko2fKcw8D2H52S1h4toUK0NLjJu3I9BEsCBbGerFVNQ9yw7T/9ygP+8P6XqTEGg5RbqI05oXpUI9J8dY4m9wGs+2kDJPwU6jvOT5rjl6Rajylgcq/XpPz+ThAi7SQPwRP94fbITSI4J8kfiRmCwrHm23V7CuBJozLU6BicJ5s5zo5t5B4x0+rYsYSHWa39YyGa3OmYCgV0sFV0O2IFPyHb5FU96d7N4ZiDeSh8MVFqcfYN4WwOgsUJ05faC3wfOwK3LxBZYKAMOgN37NUGLmMDYcbXjHHdtUWgDRDhQ="
language: node_js

node_js:
  - 10

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "manjusaka"
  - git config user.email "me@manjusaka.me"
  - git add -A
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
