env:
  global:
    - GH_REF: github.com/Zheaoli/zheaoli.github.io.git
    - secure: "AJJDb4oURU51UeMyMmik/oDhvacGcXtzw3IPJKT6eo29wv4M245sck6T40KmAc2XczsMkX/f+FCPLmoK7p8YywfwTfV/gzHgMsT6aLLoZfveTEvkZpHltQ7XHw+UPUOpW5HWBKsRGz71MPz+/RSMxpwJZK1YLmRFh6jiCqYqTOF+YV5rMpHvlwCkz1XIml+tdYX7E0bhhGmkO7mbg3IoHwHAigdXzYn+5k4xOQMj3aTadXdCbHlb3fldpF9sYcUUl8g14joo0bxmgj5rU9t/WYJClyM2qjNDwAItvVUOTM6O0Td+VeAG64rK1puMwVgsR9MXuowpo2qpmHoA1zwiDMKjjKz23KU+DeOfN/QGUSlcNwqtYW6jPPsOPFXySA4rcDCMbdXH8NbtCPVacxV6laFTU1l3D6HG8AMJ7sX2cl5wXFB8nSoMGSOLdFR6p1zJXMeQS/QlPA2erXv3ujMx+EBZQS+Jwn3nOkEWl29JHjkkeAI+rsre5e56OO5eXU1HXXZLiOhq8iVSajD+l3KFbjEVbv3XA4WxGtqcP5QhW6+o7I+8LqNyL8Ww0LjdnymY9yQ25d4LE1iV2LMOnuSGBLGq3toBkD/CcgTgH5WGVhVX1kDq27yhTHW8dtgxvJBossywWlVwozYQSxtQ4Laz1k16L1eWZ/dXCsx1DNkofi4="
language: node_js

node_js:
  - 10

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "manjusaka"
  - git config user.email "me@manjusaka.me"
  - git add -A
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
